export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_LIST_BY_USERID_REQUEST = "ORDER_LIST_BY_USERID_REQUEST";
export const ORDER_LIST_BY_USERID_SUCCESS = "ORDER_LIST_BY_USERID_SUCCESS";
export const ORDER_LIST_BY_USERID_FAIL = "ORDER_LIST_BY_USERID_FAIL";

export const ORDER_ADD_REQUEST = "ORDER_ADD_REQUEST";
export const ORDER_ADD_SUCCESS = "ORDER_ADD_SUCCESS";
export const ORDER_ADD_FAIL = "ORDER_ADD_FAIL";
export const ORDER_ADD_RESET = "ORDER_ADD_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_UPDATE_TO_PAY_REQUEST = "ORDER_UPDATE_TO_PAY_REQUEST";
export const ORDER_UPDATE_TO_PAY_SUCCESS = "ORDER_UPDATE_TO_PAY_SUCCESS";
export const ORDER_UPDATE_TO_PAY_FAIL = "ORDER_UPDATE_TO_PAY_FAIL";
export const ORDER_UPDATE_TO_PAY_RESET = "ORDER_UPDATE_TO_PAY_RESET";

export const ORDER_UPDATE_TO_DELIVERED_REQUEST =
  "ORDER_UPDATE_TO_DELIVERED_REQUEST";
export const ORDER_UPDATE_TO_DELIVERED_SUCCESS =
  "ORDER_UPDATE_TO_DELIVERED_SUCCESS";
export const ORDER_UPDATE_TO_DELIVERED_FAIL = "ORDER_UPDATE_TO_DELIVERED_FAIL";
export const ORDER_UPDATE_TO_DELIVERED_RESET =
  "ORDER_UPDATE_TO_DELIVERED_RESET";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";
