export const PRODUCT_UPDATE_TO_TRENDING_REQUEST =
  "PRODUCT_UPDATE_TO_TRENDING_REQUEST";
export const PRODUCT_UPDATE_TO_TRENDING_SUCCESS =
  "PRODUCT_UPDATE_TO_TRENDING_SUCCESS";
export const PRODUCT_UPDATE_TO_TRENDING_FAIL =
  "PRODUCT_UPDATE_TO_TRENDING_FAIL";
export const PRODUCT_UPDATE_TO_TRENDING_RESET =
  "PRODUCT_UPDATE_TO_TRENDING_RESET";

export const CREATE_LOVED_PRODUCT_REQUEST = "CREATE_LOVED_PRODUCT_REQUEST";
export const CREATE_LOVED_PRODUCT_SUCCESS = "CREATE_LOVED_PRODUCT_SUCCESS";
export const CREATE_LOVED_PRODUCT_FAIL = "CREATE_LOVED_PRODUCT_FAIL";
export const CREATE_LOVED_PRODUCT_RESET = "CREATE_LOVED_PRODUCT_RESET";

export const GET_LOVED_PRODUCT_REQUEST = "GET_LOVED_PRODUCT_REQUEST";
export const GET_LOVED_PRODUCT_SUCCESS = "GET_LOVED_PRODUCT_SUCCESS";
export const GET_LOVED_PRODUCT_FAIL = "GET_LOVED_PRODUCT_FAIL";

export const CREATE_PRODUCT_REVIEW_REQUEST = "CREATE_PRODUCT_REVIEW_REQUEST";
export const CREATE_PRODUCT_REVIEW_SUCCESS = "CREATE_PRODUCT_REVIEW_SUCCESS";
export const CREATE_PRODUCT_REVIEW_FAIL = "CREATE_PRODUCT_REVIEW_FAIL";
export const CREATE_PRODUCT_REVIEW_RESET = "CREATE_PRODUCT_REVIEW_RESET";
