export const ABOUTUS_LIST_REQUEST = "ABOUTUS_LIST_REQUEST";
export const ABOUTUS_LIST_SUCCESS = "ABOUTUS_LIST_SUCCESS";
export const ABOUTUS_LIST_FAIL = "ABOUTUS_LIST_FAIL";

export const ABOUTUS_UPDATE_REQUEST = "ABOUTUS_UPDATE_REQUEST";
export const ABOUTUS_UPDATE_SUCCESS = "ABOUTUS_UPDATE_SUCCESS";
export const ABOUTUS_UPDATE_FAIL = "ABOUTUS_UPDATE_FAIL";
export const ABOUTUS_UPDATE_RESET = "ABOUTUS_UPDATE_RESET";
