export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_UPDATE_TO_PUBLISH_REQUEST = "BLOG_UPDATE_TO_PUBLISH_REQUEST";
export const BLOG_UPDATE_TO_PUBLISH_SUCCESS = "BLOG_UPDATE_TO_PUBLISH_SUCCESS";
export const BLOG_UPDATE_TO_PUBLISH_FAIL = "BLOG_UPDATE_TO_PUBLISH_FAIL";
export const BLOG_UPDATE_TO_PUBLISH_RESET = "BLOG_UPDATE_TO_PUBLISH_RESET";
