export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_SINGLE_CATEGORY = "ADD_SINGLE_CATEGORY";

export const CHILD_CATEGORY_IMAGE_LIST_REQUEST =
  "CHILD_CATEGORY_IMAGE_LIST_REQUEST";
export const CHILD_CATEGORY_IMAGE_LIST_SUCCESS =
  "CHILD_CATEGORY_IMAGE_LIST_SUCCESS";
export const CHILD_CATEGORY_IMAGE_LIST_FAIL = "CHILD_CATEGORY_IMAGE_LIST_FAIL";

export const CHILD_CATEGORY_IMAGE_DETAIL_REQUEST =
  "CHILD_CATEGORY_IMAGE_DETAIL_REQUEST";
export const CHILD_CATEGORY_IMAGE_DETAIL_SUCCESS =
  "CHILD_CATEGORY_IMAGE_DETAIL_SUCCESS";
export const CHILD_CATEGORY_IMAGE_DETAIL_FAIL =
  "CHILD_CATEGORY_IMAGE_DETAIL_FAIL";

export const CHILD_CATEGORY_IMAGE_ADD_REQUEST =
  "CHILD_CATEGORY_IMAGE_ADD_REQUEST";
export const CHILD_CATEGORY_IMAGE_ADD_SUCCESS =
  "CHILD_CATEGORY_IMAGE_ADD_SUCCESS";
export const CHILD_CATEGORY_IMAGE_ADD_FAIL = "CHILD_CATEGORY_IMAGE_ADD_FAIL";
export const CHILD_CATEGORY_IMAGE_ADD_RESET = "CHILD_CATEGORY_IMAGE_ADD_RESET";

export const CHILD_CATEGORY_IMAGE_UPDATE_REQUEST =
  "CHILD_CATEGORY_IMAGE_UPDATE_REQUEST";
export const CHILD_CATEGORY_IMAGE_UPDATE_SUCCESS =
  "CHILD_CATEGORY_IMAGE_UPDATE_SUCCESS";
export const CHILD_CATEGORY_IMAGE_UPDATE_FAIL =
  "CHILD_CATEGORY_IMAGE_UPDATE_FAIL";
export const CHILD_CATEGORY_IMAGE_UPDATE_RESET =
  "CHILD_CATEGORY_IMAGE_UPDATE_RESET";

export const CHILD_CATEGORY_IMAGE_DELETE_REQUEST =
  "CHILD_CATEGORY_IMAGE_DELETE_REQUEST";
export const CHILD_CATEGORY_IMAGE_DELETE_SUCCESS =
  "CHILD_CATEGORY_IMAGE_DELETE_SUCCESS";
export const CHILD_CATEGORY_IMAGE_DELETE_FAIL =
  "CHILD_CATEGORY_IMAGE_DELETE_FAIL";
