export const HELP_LIST_REQUEST = "HELP_LIST_REQUEST";
export const HELP_LIST_SUCCESS = "HELP_LIST_SUCCESS";
export const HELP_LIST_FAIL = "HELP_LIST_FAIL";

export const HELP_UPDATE_REQUEST = "HELP_UPDATE_REQUEST";
export const HELP_UPDATE_SUCCESS = "HELP_UPDATE_SUCCESS";
export const HELP_UPDATE_FAIL = "HELP_UPDATE_FAIL";
export const HELP_UPDATE_RESET = "HELP_UPDATE_RESET";
