export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_UPDATE_TO_DELIVERED_REQUEST =
  "ORDER_UPDATE_TO_DELIVERED_REQUEST";
export const ORDER_UPDATE_TO_DELIVERED_SUCCESS =
  "ORDER_UPDATE_TO_DELIVERED_SUCCESS";
export const ORDER_UPDATE_TO_DELIVERED_FAIL = "ORDER_UPDATE_TO_DELIVERED_FAIL";
export const ORDER_UPDATE_TO_DELIVERED_RESET =
  "ORDER_UPDATE_TO_DELIVERED_RESET";
